name = "CFML (Script)"
grammar = "cfscript"
path_suffixes = ["cfs"]
first_line_pattern = "^\\s*(/\\*|//|component|interface|abstract)"
autoclose_before = ";:.,=}])>"
block_comment = ["/* ", " */"]
brackets = [
    { start = "{", end = "}", close = true, newline = true },
    { start = "[", end = "]", close = true, newline = true },
    { start = "(", end = ")", close = true, newline = true },
    { start = "\"", end = "\"", close = true, newline = false, not_in = [
        "comment",
        "string",
    ] },
    { start = "<", end = ">", close = false, newline = true, not_in = [
        "comment",
        "string",
    ] },
    { start = "!--", end = " --", close = true, newline = false, not_in = [
        "comment",
        "string",
    ] },
]
prettier_parser_name = "cfscript"
word_characters = ["-"]
