name = "CFML (Markup)"
grammar = "cfhtml"
path_suffixes = ["cfm", "cfml"]
autoclose_before = ";:.,=}])>"
block_comment = { start = "<!---", prefix = "", end = "--->", tab_size = 0 }
brackets = [
    { start = "{", end = "}", close = true, newline = true },
    { start = "[", end = "]", close = true, newline = true },
    { start = "(", end = ")", close = true, newline = true },
    { start = "\"", end = "\"", close = true, newline = false, not_in = ["comment", "string"] },
    { start = "<", end = ">", close = false, newline = true, not_in = ["comment", "string"] },
    { start = "!--", end = " --", close = true, newline = false, not_in = ["comment", "string"] },
]
prettier_parser_name = "cfhtml"
word_characters = ["-"]
